### ISSUE TITLE
LocationLayer 0.3.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#149]
### LocationLayer 0.3.0
  - [x] ~~when location layer is created listen to style reloading, recreate the LocationLayer, the locaiton layer has the same lifetime as the associated style~~  -> #196 
  - [x] ~~applyStyle needs to call into setProperties at runtime and not recreate LocationLayer~~ -> #196 
  - [x] ~~Expose api for last known location https://github.com/mapbox/mapbox-plugins-android/issues/136~~  -> #199 
  - [ ] Optimise for cases as #126. 
 - [x] Fix test app issues as https://github.com/mapbox/mapbox-plugins-android/issues/89.
 - [x] ~~expose click events https://github.com/mapbox/mapbox-plugins-android/issues/134~~ -> #198 
 - [x] rework sources to incorporate the full location model into 1 source 
-  [x] ~~add Circle Accuracy Layer https://github.com/mapbox/mapbox-plugins-android/issues/79~~ -> https://github.com/mapbox/mapbox-plugins-android/pull/186
 - [x] ~~keep source/layer in memory instead of calling `mapboxMap#getSource/getLayer`~~-> #196
 - [x]  ~~redo apply style so the plugin calls into `Layer.setProperties`, should fix https://github.com/mapbox/mapbox-plugins-android/issues/87.~~ -> #196
 - [ ] expose api to tweak animation, related to https://github.com/mapbox/mapbox-plugins-android/issues/53
 - [ ] if location isn't found in the camera bounds do not animate. When the it returns, move instantly. (don't animate from previous location) https://github.com/mapbox/mapbox-plugins-android/issues/64. Good use-case for something as a custom source, for now use a different tracking mechanism. 
 - [ ] add stale state https://github.com/mapbox/mapbox-plugins-android/issues/58
 - [ ] add symbol layer text api https://github.com/mapbox/mapbox-plugins-android/issues/59
 - [ ] update design, see design repo
 - [ ] tracking mode changes in https://github.com/mapbox/mapbox-plugins-android/issues/217

@mapbox/navigation-android @mapbox/android @lilykaiser

**Comment by cammace** [comment]
I've moved the remaining issues to the 0.4.0 milestone, we can use the individual tickets to track the issues.
